
import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from '@/utils/provider';
import Headers from '@/components/headers';
import Footers from '@/components/footers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Stockers',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body>
      <AntdRegistry>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Headers />
            <main className="flex-grow">{children}</main>
            <Footers />
          </div>
        </Providers>
      </AntdRegistry>
    </body>
  </html>
);

export default RootLayout;