import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';
import { Toaster } from "sonner";
import ContextProvider from './context'; // 👈 ini adalah komponen client

export const metadata: Metadata = {
  title: 'Stockers',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ContextProvider> {/* 👈 komponen client */}
            {children}
          </ContextProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
